[package]
name = "annelid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#clap = "*"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
#scan_fmt = "0.2.6"
websocket = "0.26.2"
livesplit-core = { version = "*", features = ["software-rendering", "font-loading"] }
epaint = "*"
eframe = "*"
egui = { version = "*", features = ["serde"] }
#egui_extras = "*"
lazy_static = "1.4.0"
strum = "0.22"
strum_macros = "0.22"
time = "0.3"
parking_lot = "*"
native-dialog = "0.6.3"
directories = "4.0.1"
roxmltree = "0.14.1"
clap = { version = "3.2.15", features = ["clap_derive", "derive"] }
toml = "0.5.9"
serde_derive = "1.0.140"

[target.'cfg(windows)'.dependencies]
native-windows-gui = "1.0.12"

# Remember to test with --release
#[profile.dev]
#opt-level = 2
#debug = true
